### ISSUE TITLE
java exception when processing dataset

### ISSUE THREAD

**Issue by SergioShen** [mwcvitkovic/Deep_Learning_On_Code_With_A_Graph_Vocabulary--Code_Preprocessor#3]
Hello, I occur an exception when processing dataset, the output is as follow:
```
Exception in thread "main" java.nio.file.NoSuchFileException: /java.base
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1755)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1220)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:341)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:312)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:251)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver.addPathToJar(JarTypeSolver.java:94)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver.<init>(JarTypeSolver.java:45)
	at com.amazon.javaparser.dloc.visualize.DataController.process(DataController.java:75)
	at com.amazon.javaparser.dloc.Main.main(Main.java:16)
```
It happens not only when I run processDataset.sh, but also when I run javaparser-dloc-3.5.14-SNAPSHOT-jar-with-dependencies.jar manually. What should I do?

**Comment by mwcvitkovic** [comment]
@badalgeek

**Comment by SergioShen** [comment]
I still don't know how to fix it 😂could you please help me? @badalgeek @mwcvitkovic

**Comment by badalgeek** [comment]
Could you please use jdk 1.8 instead of higher version?

**Comment by SergioShen** [comment]
jdk 1.8 seems to work. Thanks a lot.
