### ISSUE TITLE
Cannot open .gml file.

### ISSUE THREAD

**Issue by nashid** [mwcvitkovic/Deep_Learning_On_Code_With_A_Graph_Vocabulary--Code_Preprocessor#9]
I have parsed file and saved the result in a .gml file.

However, the [yEd app](https://www.yworks.com/products/yed) fails to show the graph. I always get the following error:

```java.io.IOException: Parse error at line 1: ParseException, did not find LETTER, EOF or ] but '<'
	at y.H.A.K.ā(Unknown Source)
	at y.H.H.ā(Unknown Source)
	at y.H.H.ā(Unknown Source)
	at y.H.G.ā(Unknown Source)
	at y.B.A.M.Đ(Unknown Source)
	at y.B.h.č(Unknown Source)
	at y.B.h.ā(Unknown Source)
	at y.B.h.ă(Unknown Source)
	at com.yworks.A.B.Z.ă(Unknown Source)
	at com.yworks.A.B.Z.ā(Unknown Source)
	at com.yworks.A.K.P.ā(Unknown Source)
	at com.yworks.A.K.P.ā(Unknown Source)
	at com.yworks.A.K.G.ā(Unknown Source)
	at com.yworks.A.K.G.ą(Unknown Source)
	at com.yworks.A.K.P$B.Ă(Unknown Source)
	at com.yworks.A.K.P.ā(Unknown Source)
	at com.yworks.A.L.D.ā(Unknown Source)
	at com.yworks.A.L.j.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at com.jidesoft.plaf.basic.BasicJideButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: ParseException, did not find LETTER, EOF or ] but '<'
	at y.H.A.K.ă(Unknown Source)
	... 55 more
```

Augmented AST I attempted to open is here: https://pastebin.com/C81rZYa2

**Comment by mwcvitkovic** [comment]
Hi @nashid, thanks for your interest.  I'm not familiar at all with the yEd app I'm afraid, so I don't think I can be much help here.  Might be better to ask experts in that library.
